### ISSUE TITLE
Not updated for some time.

### ISSUE THREAD

**Issue by MariasStory** [frida/cryptoshark#4]
Hi,

This project is not updated for some time. Is there another repository?

**Comment by oleavr** [comment]
Hi,

No this is it. I wrote CryptoShark to show-case Frida's Stalker API, and haven't had time to spend on it since then, and at this point I'm hoping that others will find it useful and contribute PRs for fixes and new features.

Cheers!

**Comment by vitsum** [comment]
Can it be used for android apps analysis? (native or java)

**Comment by einsteinx2** [comment]
@oleavr looks like it's not currently possible to download either the binaries or the QT files necessary to compile as build.frida.re seems to be completely broken. Is there an alternative download location somewhere? I'd really like to try this out.

**Comment by oleavr** [comment]
@einsteinx2 Prebuilt QML bindings are available from our releases page: https://github.com/frida/frida/releases

**Comment by oleavr** [comment]
(Only for macOS for now, but it's easy to build yourself on other OSes: set `FRIDA` env var to point to your `frida` repo where frida-core has been built, then follow the standard Qt qmake steps for frida-qml.)

**Comment by oleavr** [comment]
CryptoShark is back:
https://github.com/frida/cryptoshark/releases/tag/0.2.0
